Update posttrans
Make the "systemctl enable" call happens only on "install", but not on "upgrade"

diff --git a/omnibus/package-scripts/agent-rpm/posttrans b/omnibus/package-scripts/agent-rpm/posttrans
--- a/omnibus/package-scripts/agent-rpm/posttrans
+++ b/omnibus/package-scripts/agent-rpm/posttrans
@@ -16,14 +16,16 @@ DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_DISTRIBUTION  || gre
 # Create a symlink to the agent's binary
 ln -sf $INSTALL_DIR/bin/agent/agent /usr/bin/datadog-agent
 
-echo "Enabling service $SERVICE_NAME"
-if command -v systemctl >/dev/null 2>&1; then
-    systemctl enable $SERVICE_NAME || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with systemctl"
-elif command -v initctl >/dev/null 2>&1; then
-    # start/stop policy is already defined in the upstart job file
-    :
-else
-    echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
+if [ "$1" -eq 1 ]; then
+    echo "Enabling service $SERVICE_NAME"
+    if command -v systemctl >/dev/null 2>&1; then
+        systemctl enable $SERVICE_NAME || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with systemctl"
+    elif command -v initctl >/dev/null 2>&1; then
+        # start/stop policy is already defined in the upstart job file
+        :
+    else
+        echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
+    fi
 fi
 
 # Only install selinux policy on a few known distributions
